### ISSUE TITLE
Backbord this library to be compatible with .NET Standard 2.0 to make it useable for more projects

### ISSUE THREAD

**Issue by mgeramb** [TheHllm/KeePassXC-API#5]
@TheHllm Thank your for providing this library. It is very helpful to me. I'am working on a project on top on it to provide an .NET configuration overlay for developer environments to provid the secrects from a KeePassXC as configuration values. 
I want to make this library .NET Standard 2.0 compatible, so that it can be used for all AspNetCore projects. For this, I would need a .NET standard libary from your project and the depending projects. I have basically checked this already and it should be an easy change.
Are you interested in PR's for this? And would you create new Nuget packages out of it?

**Comment by TheHllm** [comment]
Yes, sure.

**Comment by mgeramb** [comment]
PR created: https://github.com/TheHllm/KeePassXC-API/pull/9
